// 4. frontend/Frontend Angular/src/app/new-ad/new-ad.component.ts
import { HttpClient } from '@angular/common/http';
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';

@Component({
  selector: 'app-new-ad',
  templateUrl: './new-ad.component.html',
  styleUrls: ['./new-ad.component.css']
})
export class NewAdComponent implements OnInit {

  tipusok: any[] = [];
  errorMessage = ''
  model = {
    kategoriaId: 0,
    leiras: '',
    hirdetesDatuma: new Date().toISOString().substring(0, 10),   
    tehermentes: true,
    kepUrl: ''
  }


  constructor(private http: HttpClient, private router: Router) { }

  ngOnInit(): void {
    this.http.get<any[]>('http://localhost:5000/api/kategoriak').subscribe({
      next: (data: any[]) => this.tipusok = data,
      error: (err) => this.errorMessage = err.message
    })
  }

  kuldes(): void {
    this.model.kategoriaId = Number(this.model.kategoriaId);
    this.http.post<any>('http://localhost:5000/api/ujingatlan', this.model).subscribe({
      next: () => this.router.navigate(['offers']),
      error: (err) => this.errorMessage = err.message
    })
  }
}

<div class="container">
    <h2 class="mb-4 text-center">Új hirdetés elküldése</h2>
    <div class="row">
        <div class="offset-lg-3 offset-md-2 col-lg-6 col-md-8 col-12">
            <div class="mb-3">
                <label for="category" class="form-label">Ingatlan kategóriája</label>
                <select class="form-select" name="kategoriaId" [(ngModel)]="model.kategoriaId">
                    <option value="0">Kérem válasszon</option>
                    <option *ngFor="let t of tipusok" [value]="t.id">{{t.megnevezes}}</option>
                </select>
            </div>

            <div class="mb-3">
                <label for="date" class="form-label">Hirdetés dátuma</label>
                <input type="date" class="form-control" name="hirdetesDatuma" [(ngModel)]="model.hirdetesDatuma">
            </div>
            <div class="mb-3">
                <label for="description" class="form-label">Ingatlan leírása</label>
                <textarea class="form-control" name="leiras" rows="3" [(ngModel)]="model.leiras"></textarea>
            </div>
            <div class="form-check mb-3">
                <input class="form-check-input" type="checkbox" name="tehermentes" [(ngModel)]="model.tehermentes">
                <label class="form-check-label" for="creditFree">Tehermentes ingatlan</label>
            </div>
            <div class="mb-3">
                <label for="pictureUrl" class="form-label">Fénykép az ingatlanról</label>
                <input type="url" class="form-control" name="kepUrl" [(ngModel)]="model.kepUrl">
            </div>
            <div class="mb-3 text-center">
                <button class="btn btn-primary px-5" (click)="kuldes()">Küldés</button>
            </div>

            <div *ngIf="errorMessage" class="alert alert-danger alert-dismissible" role="alert">
                <strong>{{errorMessage}}</strong>
                <button type="button" class="btn-close" (click)="errorMessage = ''"></button>
            </div>

        </div>
    </div>
</div>

// 4. frontend/Frontend_Vue3_Quasar/src/pages/newad.vue
<script setup lang="ts">
  import { useStore1 } from "../store/store1";
  import { useStoreN } from "../store/storeN";
  import { date } from "quasar";
  //   import router from "src/router";

  const storeN = useStoreN();
  const store1 = useStore1();

  onMounted(() => {
    store1.getAll();
    storeN.data = {
      hirdetesDatuma: date.formatDate(new Date(), "YYYY-MM-DD"),
      tehermentes: true,
    };
  });

  function onSubmit() {
    storeN.create();
  }
</script>

<template>
  <q-page>
    <div class="row justify-center q-pa-md">
      <div class="col-12 col-sm-8 col-md-6 col-lg-4">
        <q-form class="q-gutter-md text-center" @submit="onSubmit">
          <h5>Új hirdetés elküldése</h5>
          <q-select
            v-model="storeN.data.kategoriaId"
            clearable
            dense
            emit-value
            label="Ingatlan kategóriája"
            map-options
            option-label="megnevezes"
            option-value="id"
            :options="store1.data1"
            outlined
            :rules="[(v) => v != null || 'Kérem válasszon!']"
          />
          <q-input
            v-model="storeN.data.hirdetesDatuma"
            clearable
            disable
            label="Hírdetés dátuma"
            outlined
            type="date"
          />
          <q-input
            v-model="storeN.data.leiras"
            dense
            label="Leírás"
            outlined
            :rules="[(v) => (v != null && v != '') || 'Kérem töltse ki a mezőt!']"
            type="textarea"
          />
          <div class="text-left">
            <q-checkbox v-model="storeN.data.tehermentes" label="Tehermentes ingatlan" />
          </div>

          <q-input
            v-model="storeN.data.kepUrl"
            dense
            label="Fénykép az ingatlanról"
            outlined
            :rules="[(v) => (v != null && v != '') || 'Kérem töltse ki a mezőt!']"
            type="url"
          />
          <q-btn class="q-px-md" color="green" label="Küldés" no-caps type="submit" />
        </q-form>
      </div>
    </div>
  </q-page>
</template>

<style lang="scss" scoped></style>
